machine:
  xcode:
    version: "7.3"
  environment:
    XCODE_SCHEME: nonce
    XCODE_WORKSPACE: nonce.xcworkspace

dependencies:
  override:
    - git submodule update --init --recursive

test:
  override:
    - bin/test
